CREATE TABLE T_CITY(
OFFICE_NAME VARCHAR(250),
PINCODE NUMBER,
OFFICE_TYPE VARCHAR(10),
DELIVERY_STATUS CHAR,
DIVISION_NAME VARCHAR(50),
REGION_NAME VARCHAR(50),
CIRCLE_NAME VARCHAR(50),
TALUK VARCHAR(50),
DISTRICT_NAME  VARCHAR(100),
STATE_NAME VARCHAR(50),
PRIMARY KEY(OFFICE_NAME)
);